[2021-05-08 11:09:48,982] {scheduler_job.py:182} INFO - Started process (PID=140146) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:09:48,985] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:09:48,990] {logging_mixin.py:104} INFO - [2021-05-08 11:09:48,987] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:09:49,640] {logging_mixin.py:104} INFO - [2021-05-08 11:09:49,599] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:09:49,640] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:09:49,740] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.761 seconds
[2021-05-08 11:10:44,832] {scheduler_job.py:182} INFO - Started process (PID=140335) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:10:44,833] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:10:44,834] {logging_mixin.py:104} INFO - [2021-05-08 11:10:44,834] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:10:45,339] {logging_mixin.py:104} INFO - [2021-05-08 11:10:45,338] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:10:45,339] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:10:45,586] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.758 seconds
[2021-05-08 11:11:34,754] {scheduler_job.py:182} INFO - Started process (PID=140487) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:11:34,756] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:11:34,758] {logging_mixin.py:104} INFO - [2021-05-08 11:11:34,757] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:11:35,244] {logging_mixin.py:104} INFO - [2021-05-08 11:11:35,243] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:11:35,245] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:11:35,332] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.580 seconds
[2021-05-08 11:12:26,406] {scheduler_job.py:182} INFO - Started process (PID=140662) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:12:26,407] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:12:26,408] {logging_mixin.py:104} INFO - [2021-05-08 11:12:26,408] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:12:27,072] {logging_mixin.py:104} INFO - [2021-05-08 11:12:27,071] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:12:27,072] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:12:27,144] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.741 seconds
[2021-05-08 11:13:06,453] {scheduler_job.py:182} INFO - Started process (PID=140786) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:13:06,456] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:13:06,457] {logging_mixin.py:104} INFO - [2021-05-08 11:13:06,457] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:13:07,068] {logging_mixin.py:104} INFO - [2021-05-08 11:13:07,067] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:13:07,069] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:13:07,156] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.707 seconds
[2021-05-08 11:13:57,134] {scheduler_job.py:182} INFO - Started process (PID=140963) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:13:57,136] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:13:57,136] {logging_mixin.py:104} INFO - [2021-05-08 11:13:57,136] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:13:57,670] {logging_mixin.py:104} INFO - [2021-05-08 11:13:57,668] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:13:57,670] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:13:57,747] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.615 seconds
[2021-05-08 11:14:51,714] {scheduler_job.py:182} INFO - Started process (PID=141180) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:14:51,715] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:14:51,715] {logging_mixin.py:104} INFO - [2021-05-08 11:14:51,715] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:14:52,227] {logging_mixin.py:104} INFO - [2021-05-08 11:14:52,226] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:14:52,228] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:14:52,304] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.593 seconds
[2021-05-08 11:15:30,933] {scheduler_job.py:182} INFO - Started process (PID=141290) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:15:30,934] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:15:30,935] {logging_mixin.py:104} INFO - [2021-05-08 11:15:30,934] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:15:31,414] {logging_mixin.py:104} INFO - [2021-05-08 11:15:31,413] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:15:31,415] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:15:31,494] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.566 seconds
[2021-05-08 11:16:23,931] {scheduler_job.py:182} INFO - Started process (PID=141446) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:16:23,933] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:16:23,934] {logging_mixin.py:104} INFO - [2021-05-08 11:16:23,933] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:16:24,506] {logging_mixin.py:104} INFO - [2021-05-08 11:16:24,505] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:16:24,507] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:16:24,596] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.670 seconds
[2021-05-08 11:17:02,209] {scheduler_job.py:182} INFO - Started process (PID=141549) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:17:02,211] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:17:02,212] {logging_mixin.py:104} INFO - [2021-05-08 11:17:02,212] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:17:02,816] {logging_mixin.py:104} INFO - [2021-05-08 11:17:02,814] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:17:02,816] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:17:02,898] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.692 seconds
[2021-05-08 11:17:58,877] {scheduler_job.py:182} INFO - Started process (PID=141742) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:17:58,880] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:17:58,883] {logging_mixin.py:104} INFO - [2021-05-08 11:17:58,882] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:17:59,403] {logging_mixin.py:104} INFO - [2021-05-08 11:17:59,402] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:17:59,403] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:17:59,489] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.616 seconds
[2021-05-08 11:18:53,991] {scheduler_job.py:182} INFO - Started process (PID=141963) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:18:53,992] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:18:53,993] {logging_mixin.py:104} INFO - [2021-05-08 11:18:53,993] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:18:54,561] {logging_mixin.py:104} INFO - [2021-05-08 11:18:54,560] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:18:54,562] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:18:54,680] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.693 seconds
[2021-05-08 11:19:48,585] {scheduler_job.py:182} INFO - Started process (PID=142129) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:19:48,587] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:19:48,588] {logging_mixin.py:104} INFO - [2021-05-08 11:19:48,588] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:19:49,090] {logging_mixin.py:104} INFO - [2021-05-08 11:19:49,089] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:19:49,091] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:19:49,182] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.599 seconds
[2021-05-08 11:20:44,705] {scheduler_job.py:182} INFO - Started process (PID=142290) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:20:44,707] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:20:44,708] {logging_mixin.py:104} INFO - [2021-05-08 11:20:44,708] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:20:45,465] {logging_mixin.py:104} INFO - [2021-05-08 11:20:45,463] {dagbag.py:308} ERROR - Failed to import: /home/navneetsajwan/airflow/dags/singer_etl.py
Traceback (most recent call last):
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/dagbag.py", line 305, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/navneetsajwan/airflow/dags/singer_etl.py", line 43, in <module>
    scriptpath = Variable.get("SINGER_DATA")
  File "/home/navneetsajwan/airflow/etl/lib/python3.8/site-packages/airflow/models/variable.py", line 128, in get
    raise KeyError(f'Variable {key} does not exist')
KeyError: 'Variable SINGER_DATA does not exist'
[2021-05-08 11:20:45,465] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:20:45,595] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.895 seconds
[2021-05-08 11:21:37,721] {scheduler_job.py:182} INFO - Started process (PID=142489) to work on /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:21:37,723] {scheduler_job.py:629} INFO - Processing file /home/navneetsajwan/airflow/dags/singer_etl.py for tasks to queue
[2021-05-08 11:21:37,724] {logging_mixin.py:104} INFO - [2021-05-08 11:21:37,724] {dagbag.py:451} INFO - Filling up the DagBag from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:21:37,724] {scheduler_job.py:641} WARNING - No viable dags retrieved from /home/navneetsajwan/airflow/dags/singer_etl.py
[2021-05-08 11:21:37,725] {scheduler_job.py:190} INFO - Processing /home/navneetsajwan/airflow/dags/singer_etl.py took 0.020 seconds
